linters:
  enable-all: true
  disable:
    - err113
    - lll
    - exportloopref
    - depguard
    - godot
    - wrapcheck
    - varnamelen
    - exhaustruct
    - ireturn
    - gochecknoglobals
    - nilnil
    - mnd
    - recvcheck
    - tagliatelle

linters-settings:
  lll:
    line-length: 180

  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  cyclop:
    max-complexity: 20
    skip-tests: true

  dupl:
    threshold: 200

  nestif:
    min-complexity: 10

  wsl:
    strict-append: false
    allow-cuddle-declarations: true

  gosec:
    excludes:
      - G115
      - G306
      - G401
      - G501

  revive:
    max-open-files: 2048
    rules:
      - name: var-naming
        disabled: true

  stylecheck:
    checks:
      - all
      - -ST1003
  exhaustive:
    check:
      - switch
      - map
    check-generated: true
    default-signifies-exhaustive: true
issues:
  exclude-files:
    - ".*_test\\.go$"
