include:
  - tests/engine/compose.yaml
services:
  ndc-storage:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./tests/configuration:/etc/connector:ro
      - ./tests/certs/service_account.json:/service_account.json
      - ./tests/certs/tls:/certs:ro
      - fs_data:/home/nonroot/data
    user: "65532:65532"
    extra_hosts:
      - local.hasura.dev=host-gateway
    environment:
      STORAGE_ENDPOINT: $STORAGE_ENDPOINT
      PUBLIC_HOST: localhost:9000
      DEFAULT_BUCKET: $DEFAULT_BUCKET
      ACCESS_KEY_ID: $ACCESS_KEY_ID
      SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
      S3_STORAGE_ENDPOINT: $S3_STORAGE_ENDPOINT
      S3_PUBLIC_HOST: localhost:9010
      S3_DEFAULT_BUCKET: $S3_DEFAULT_BUCKET
      S3_ACCESS_KEY_ID: $S3_ACCESS_KEY_ID
      S3_SECRET_ACCESS_KEY: $S3_SECRET_ACCESS_KEY
      AZURE_STORAGE_ENDPOINT: $AZURE_STORAGE_ENDPOINT
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_ACCOUNT_KEY};BlobEndpoint=${AZURE_STORAGE_ENDPOINT}
      AZURE_STORAGE_DEFAULT_BUCKET: $AZURE_STORAGE_DEFAULT_BUCKET
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_KEY: $AZURE_STORAGE_ACCOUNT_KEY
      GOOGLE_STORAGE_DEFAULT_BUCKET: $GOOGLE_STORAGE_DEFAULT_BUCKET
      GOOGLE_STORAGE_ENDPOINT: $GOOGLE_STORAGE_ENDPOINT
      GOOGLE_STORAGE_PUBLIC_HOST: $GOOGLE_STORAGE_PUBLIC_HOST
      GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID
      GOOGLE_STORAGE_CREDENTIALS_FILE: /service_account.json
      HASURA_LOG_LEVEL: debug
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRICS_EXPORTER: prometheus
      STORAGE_FS_DEFAULT_DIRECTORY: /home/nonroot/data
      TLS_CERT_FILE: /certs/client.crt
      TLS_KEY_FILE: /certs/client.key
      TLS_CA_FILE: /certs/ca.crt

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: $ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: $SECRET_ACCESS_KEY
    command: server /data --console-address ":9001"

  # https://github.com/adobe/S3Mock
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
      - initialBuckets=bucket1
    ports:
      - 9010:9090
      - 9111:9191
    volumes:
      - s3_data:/containers3root

  # https://github.com/Azure/Azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    command:
      [
        "azurite-blob",
        "--blobHost",
        "0.0.0.0",
        "-d",
        "/debug.log",
        "--cert",
        "/certs/server.crt",
        "--key",
        "/certs/server.key",
      ]
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - "10000:10000"
    volumes:
      - ./tests/certs/tls:/certs:ro
    environment:
      AZURITE_ACCOUNTS: "${AZURE_STORAGE_ACCOUNT_NAME}:${AZURE_STORAGE_ACCOUNT_KEY}"

  # https://github.com/fsouza/fake-gcs-server
  gcp-storage-emulator:
    image: fsouza/fake-gcs-server:1.52.2
    command:
      [
        "-public-host",
        "https://local.hasura.dev:4443",
        "-log-level",
        "debug",
        "--cert-location",
        "/certs/server.crt",
        "--private-key-location",
        "/certs/server.key",
      ]
    ports:
      - "4443:4443"
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ./tests/certs/tls:/certs:ro

volumes:
  minio_data:
  s3_data:
  fs_data:
