include:
  - tests/engine/compose.yaml
services:
  ndc-storage:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./tests/configuration:/etc/connector:ro
    extra_hosts:
      - local.hasura.dev=host-gateway
    environment:
      STORAGE_ENDPOINT: $STORAGE_ENDPOINT
      PUBLIC_HOST: localhost:9000
      DEFAULT_BUCKET: $DEFAULT_BUCKET
      ACCESS_KEY_ID: $ACCESS_KEY_ID
      SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
      S3_STORAGE_ENDPOINT: $S3_STORAGE_ENDPOINT
      S3_PUBLIC_HOST: localhost:9010
      S3_DEFAULT_BUCKET: $S3_DEFAULT_BUCKET
      S3_ACCESS_KEY_ID: $S3_ACCESS_KEY_ID
      S3_SECRET_ACCESS_KEY: $S3_SECRET_ACCESS_KEY
      AZURE_STORAGE_ENDPOINT: http://azurite:10000
      AZURE_STORAGE_PUBLIC_HOST: http://localhost:10000
      AZURE_STORAGE_DEFAULT_BUCKET: azure-test
      HASURA_LOG_LEVEL: debug
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRICS_EXPORTER: prometheus

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: $ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: $SECRET_ACCESS_KEY
    command: server /data --console-address ":9001"

  # https://github.com/adobe/S3Mock
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
      - initialBuckets=bucket1
    ports:
      - 9010:9090
      - 9111:9191
    volumes:
      - s3_data:/containers3root

  # https://github.com/Azure/Azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

volumes:
  minio_data:
  s3_data:
