// Code generated by github.com/hasura/ndc-sdk-go/cmd/hasura-ndc-go, DO NOT EDIT.
package connector

import (
	"github.com/hasura/ndc-sdk-go/schema"
)

func toPtr[V any](value V) *V {
	return &value
}

// GetConnectorSchema gets the generated connector schema
func GetConnectorSchema() *schema.SchemaResponse {
	return &schema.SchemaResponse{
		Collections: []schema.CollectionInfo{},
		ObjectTypes: schema.SchemaResponseObjectTypes{
			"BucketAutoclass": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"enabled": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"terminalStorageClass": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"terminalStorageClassUpdateTime": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"toggleTime": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
				},
			},
			"BucketCors": schema.ObjectType{
				Description: toPtr("is the bucket's Cross-Origin Resource Sharing (CORS) configuration."),
				Fields: schema.ObjectTypeFields{
					"maxAge": schema.ObjectField{
						Type: schema.NewNamedType("Duration").Encode(),
					},
					"methods": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
					"origins": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
					"responseHeaders": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"BucketHierarchicalNamespace": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"enabled": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
				},
			},
			"BucketLogging": schema.ObjectType{
				Description: toPtr("holds the bucket's logging configuration, which defines the destination bucket and optional name prefix for the current bucket's logs."),
				Fields: schema.ObjectTypeFields{
					"logBucket": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"logObjectPrefix": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"BucketWebsite": schema.ObjectType{
				Description: toPtr("holds the bucket's website configuration, controlling how the service behaves when accessing bucket contents as a web site. See https://cloud.google.com/storage/docs/static-website for more information."),
				Fields: schema.ObjectTypeFields{
					"mainPageSuffix": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"notFoundPage": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"CustomPlacementConfig": schema.ObjectType{
				Description: toPtr("holds the bucket's custom placement configuration for Custom Dual Regions. See https://cloud.google.com/storage/docs/locations#location-dr for more information."),
				Fields: schema.ObjectTypeFields{
					"DataLocations": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"GetStorageObjectOptions": schema.ObjectType{
				Description: toPtr("are used to specify additional headers or options during GET requests."),
				Fields: schema.ObjectTypeFields{
					"headers": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"partNumber": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"requestParams": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"ListIncompleteUploadsOptions": schema.ObjectType{
				Description: toPtr("the input arguments of the ListIncompleteUploads method."),
				Fields: schema.ObjectTypeFields{
					"prefix": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"ListStorageObjectsArguments": schema.ObjectType{
				Description: toPtr("holds all arguments of a list object request."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"hierarchy": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"maxResults": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"prefix": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"startAfter": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			"MakeStorageBucketOptions": schema.ObjectType{
				Description: toPtr("holds all options to tweak bucket creation."),
				Fields: schema.ObjectTypeFields{
					"name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"objectLock": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"region": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
				},
			},
			"ObjectAbortIncompleteMultipartUpload": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"daysAfterInitiation": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
				},
			},
			"ObjectLifecycleAllVersionsExpiration": schema.ObjectType{
				Description: toPtr("represents AllVersionsExpiration actions element in an ILM policy"),
				Fields: schema.ObjectTypeFields{
					"days": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"deleteMarker": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
				},
			},
			"ObjectLifecycleConfiguration": schema.ObjectType{
				Description: toPtr("is a collection of lifecycle Rule objects."),
				Fields: schema.ObjectTypeFields{
					"rules": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("ObjectLifecycleRule")).Encode(),
					},
				},
			},
			"ObjectLifecycleDelMarkerExpiration": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"days": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
				},
			},
			"ObjectLifecycleExpiration": schema.ObjectType{
				Description: toPtr("expiration details of lifecycle configuration"),
				Fields: schema.ObjectTypeFields{
					"date": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Date")).Encode(),
					},
					"days": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"expiredObjectAllVersions": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"expiredObjectDeleteMarker": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
				},
			},
			"ObjectLifecycleFilter": schema.ObjectType{
				Description: toPtr("will be used in selecting rule(s) for lifecycle configuration"),
				Fields: schema.ObjectTypeFields{
					"matchesPrefix": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"matchesStorageClasses": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"matchesSuffix": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"objectSizeGreaterThan": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"objectSizeLessThan": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
				},
			},
			"ObjectLifecycleNoncurrentVersionExpiration": schema.ObjectType{
				Description: toPtr("- Specifies when noncurrent object versions expire. Upon expiration, server permanently deletes the noncurrent object versions. Set this lifecycle configuration action on a bucket that has versioning enabled (or suspended) to request server delete noncurrent object versions at a specific period in the object's lifetime."),
				Fields: schema.ObjectTypeFields{
					"newerNoncurrentVersions": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"noncurrentDays": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
				},
			},
			"ObjectLifecycleNoncurrentVersionTransition": schema.ObjectType{
				Description: toPtr("sets this action to request server to transition noncurrent object versions to different set storage classes at a specific period in the object's lifetime."),
				Fields: schema.ObjectTypeFields{
					"newerNoncurrentVersions": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"noncurrentDays": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"ObjectLifecycleRule": schema.ObjectType{
				Description: toPtr("represents a single rule in lifecycle configuration"),
				Fields: schema.ObjectTypeFields{
					"abortIncompleteMultipartUpload": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectAbortIncompleteMultipartUpload")).Encode(),
					},
					"allVersionsExpiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleAllVersionsExpiration")).Encode(),
					},
					"delMarkerExpiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleDelMarkerExpiration")).Encode(),
					},
					"enabled": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"expiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleExpiration")).Encode(),
					},
					"filter": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("ObjectLifecycleFilter"))).Encode(),
					},
					"id": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"noncurrentVersionExpiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleNoncurrentVersionExpiration")).Encode(),
					},
					"noncurrentVersionTransition": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleNoncurrentVersionTransition")).Encode(),
					},
					"prefix": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"transition": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleTransition")).Encode(),
					},
				},
			},
			"ObjectLifecycleTransition": schema.ObjectType{
				Description: toPtr("transition details of lifecycle configuration"),
				Fields: schema.ObjectTypeFields{
					"date": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Date")).Encode(),
					},
					"days": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"PresignedGetStorageObjectOptions": schema.ObjectType{
				Description: toPtr("represent the options for the PresignedGetObject method."),
				Fields: schema.ObjectTypeFields{
					"expiry": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Duration")).Encode(),
					},
					"requestParams": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
				},
			},
			"PresignedURLResponse": schema.ObjectType{
				Description: toPtr("holds the presigned URL and expiry information."),
				Fields: schema.ObjectTypeFields{
					"expiredAt": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"url": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"PutStorageObjectArguments": schema.ObjectType{
				Description: toPtr("represents input arguments of the PutObject method."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"object": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"options": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("PutStorageObjectOptions")).Encode(),
					},
					"where": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			"PutStorageObjectOptions": schema.ObjectType{
				Description: toPtr("represents options specified by user for PutObject call."),
				Fields: schema.ObjectTypeFields{
					"autoChecksum": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ChecksumType")).Encode(),
					},
					"cacheControl": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksum": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ChecksumType")).Encode(),
					},
					"concurrentStreamParts": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"contentDisposition": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentEncoding": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentLanguage": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentType": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"disableContentSha256": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"disableMultipart": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"expires": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"legalHold": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"metadata": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"numThreads": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"partSize": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"retention": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("PutStorageObjectRetentionOptions")).Encode(),
					},
					"sendContentMd5": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"websiteRedirectLocation": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"PutStorageObjectRetentionOptions": schema.ObjectType{
				Description: toPtr("represent options of object retention configuration."),
				Fields: schema.ObjectTypeFields{
					"governanceBypass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"mode": schema.ObjectField{
						Type: schema.NewNamedType("StorageRetentionMode").Encode(),
					},
					"retainUntilDate": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
				},
			},
			"RemoveStorageObjectError": schema.ObjectType{
				Description: toPtr("the container of Multi Delete S3 API error."),
				Fields: schema.ObjectTypeFields{
					"error": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"objectName": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"RemoveStorageObjectOptions": schema.ObjectType{
				Description: toPtr("represents options specified by user for RemoveObject call."),
				Fields: schema.ObjectTypeFields{
					"forceDelete": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"governanceBypass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"softDelete": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"ServerSideEncryptionConfiguration": schema.ObjectType{
				Description: toPtr("is the default encryption configuration structure."),
				Fields: schema.ObjectTypeFields{
					"kmsMasterKeyId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"sseAlgorithm": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"SetStorageObjectLockConfig": schema.ObjectType{
				Description: toPtr("represents the object lock configuration options in given bucket"),
				Fields: schema.ObjectTypeFields{
					"mode": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionMode")).Encode(),
					},
					"unit": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionValidityUnit")).Encode(),
					},
					"validity": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
				},
			},
			"SetStorageObjectRetentionOptions": schema.ObjectType{
				Description: toPtr("represents options specified by user for PutObject call."),
				Fields: schema.ObjectTypeFields{
					"governanceBypass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"mode": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionMode")).Encode(),
					},
					"retainUntilDate": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
				},
			},
			"StorageBucket": schema.ObjectType{
				Description: toPtr("the container for bucket metadata."),
				Fields: schema.ObjectTypeFields{
					"autoclass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("BucketAutoclass")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"cors": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("BucketCors"))).Encode(),
					},
					"creationTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"customPlacementConfig": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("CustomPlacementConfig")).Encode(),
					},
					"defaultEventBasedHold": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"encryption": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ServerSideEncryptionConfiguration")).Encode(),
					},
					"etag": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"hierarchicalNamespace": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("BucketHierarchicalNamespace")).Encode(),
					},
					"lastModified": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"lifecycle": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleConfiguration")).Encode(),
					},
					"locationType": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"logging": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("BucketLogging")).Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"objectLock": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageObjectLockConfig")).Encode(),
					},
					"region": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"requesterPays": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"rpo": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("GoogleStorageRPO")).Encode(),
					},
					"softDeletePolicy": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageObjectSoftDeletePolicy")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versioning": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageBucketVersioningConfiguration")).Encode(),
					},
					"website": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("BucketWebsite")).Encode(),
					},
				},
			},
			"StorageBucketArguments": schema.ObjectType{
				Description: toPtr("represent the common input arguments for bucket-related methods."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
				},
			},
			"StorageBucketListResults": schema.ObjectType{
				Description: toPtr("hold the paginated results of the storage bucket list."),
				Fields: schema.ObjectTypeFields{
					"buckets": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("StorageBucket")).Encode(),
					},
					"pageInfo": schema.ObjectField{
						Type: schema.NewNamedType("StoragePaginationInfo").Encode(),
					},
				},
			},
			"StorageBucketVersioningConfiguration": schema.ObjectType{
				Description: toPtr("is the versioning configuration structure"),
				Fields: schema.ObjectTypeFields{
					"enabled": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"excludeFolders": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"excludedPrefixes": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"mfaDelete": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageCopyDestOptions": schema.ObjectType{
				Description: toPtr("represents options specified by user for CopyObject/ComposeObject APIs."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"legalHold": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"metadata": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"mode": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionMode")).Encode(),
					},
					"object": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"retainUntilDate": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"size": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
				},
			},
			"StorageCopySrcOptions": schema.ObjectType{
				Description: toPtr("represents a source object to be copied, using server-side copying APIs."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"end": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"matchETag": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"matchModifiedSince": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"matchRange": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"matchUnmodifiedSince": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"noMatchETag": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"object": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"start": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageGrant": schema.ObjectType{
				Description: toPtr("holds grant information."),
				Fields: schema.ObjectTypeFields{
					"grantee": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageGrantee")).Encode(),
					},
					"permission": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageGrantee": schema.ObjectType{
				Description: toPtr("represents the person being granted permissions."),
				Fields: schema.ObjectTypeFields{
					"displayName": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"id": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"uri": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageObject": schema.ObjectType{
				Description: toPtr("container for object metadata."),
				Fields: schema.ObjectTypeFields{
					"accessTierChangeTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"accessTierInferred": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"acl": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"archiveStatus": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"blobSequenceNumber": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"blobType": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"bucket": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"cacheControl": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc32C": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc64Nvme": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha1": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha256": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"contentDisposition": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentEncoding": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentLanguage": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentMd5": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"contentType": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"copy": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageObjectCopyInfo")).Encode(),
					},
					"creationTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"customerProvidedKeySha256": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"deleted": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"deletedTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"destinationSnapshot": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"etag": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"expiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"expirationRuleId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"expires": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"grant": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("StorageGrant"))).Encode(),
					},
					"group": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"incrementalCopy": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"isDirectory": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"isLatest": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"kmsKeyName": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"lastAccessTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"lastModified": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"leaseDuration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"leaseState": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"leaseStatus": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"legalHold": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"mediaLink": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"metadata": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"owner": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageOwner")).Encode(),
					},
					"permissions": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"rawMetadata": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"rehydratePriority": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"remainingRetentionDays": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"replicationReady": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"replicationStatus": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageObjectReplicationStatus")).Encode(),
					},
					"resourceType": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"restore": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRestoreInfo")).Encode(),
					},
					"retentionMode": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"retentionUntilDate": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"sealed": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"serverEncrypted": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"size": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"tagCount": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageObjectChecksum": schema.ObjectType{
				Description: toPtr("represents checksum values of the object."),
				Fields: schema.ObjectTypeFields{
					"checksumCrc32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc32C": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc64Nvme": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha1": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha256": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageObjectCopyInfo": schema.ObjectType{
				Description: toPtr("holds the copy information if the object was copied from another object."),
				Fields: schema.ObjectTypeFields{
					"completionTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"id": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"progress": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"source": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"status": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"statusDescription": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageObjectListResults": schema.ObjectType{
				Description: toPtr("hold the paginated results of the storage object list."),
				Fields: schema.ObjectTypeFields{
					"objects": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("StorageObject")).Encode(),
					},
					"pageInfo": schema.ObjectField{
						Type: schema.NewNamedType("StoragePaginationInfo").Encode(),
					},
				},
			},
			"StorageObjectLockConfig": schema.ObjectType{
				Description: toPtr("represents the object lock configuration in given bucket"),
				Fields: schema.ObjectTypeFields{
					"enabled": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"mode": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionMode")).Encode(),
					},
					"unit": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("StorageRetentionValidityUnit")).Encode(),
					},
					"validity": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
				},
			},
			"StorageObjectMultipartInfo": schema.ObjectType{
				Description: toPtr("container for multipart object metadata."),
				Fields: schema.ObjectTypeFields{
					"initiated": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"size": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"storageClass": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"uploadId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StorageObjectSoftDeletePolicy": schema.ObjectType{
				Description: toPtr("contains the bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted."),
				Fields: schema.ObjectTypeFields{
					"effectiveTime": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"retentionDuration": schema.ObjectField{
						Type: schema.NewNamedType("Duration").Encode(),
					},
				},
			},
			"StorageOwner": schema.ObjectType{
				Description: toPtr("name."),
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"StoragePaginationInfo": schema.ObjectType{
				Description: toPtr("holds the pagination information."),
				Fields: schema.ObjectTypeFields{
					"cursor": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"hasNextPage": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
				},
			},
			"StorageRestoreInfo": schema.ObjectType{
				Description: toPtr("contains information of the restore operation of an archived object."),
				Fields: schema.ObjectTypeFields{
					"expiryTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"ongoingRestore": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
				},
			},
			"StorageUploadInfo": schema.ObjectType{
				Description: toPtr("represents the information of the uploaded object."),
				Fields: schema.ObjectTypeFields{
					"bucket": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"checksumCrc32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc32C": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumCrc64Nvme": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha1": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"checksumSha256": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"contentMd5": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"etag": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"expiration": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"expirationRuleId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"lastModified": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"location": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"size": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			"UpdateStorageBucketOptions": schema.ObjectType{
				Description: toPtr("hold update options for the bucket."),
				Fields: schema.ObjectTypeFields{
					"encryption": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ServerSideEncryptionConfiguration")).Encode(),
					},
					"lifecycle": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleConfiguration")).Encode(),
					},
					"objectLock": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("SetStorageObjectLockConfig")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versioningEnabled": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
				},
			},
			"UpdateStorageObjectOptions": schema.ObjectType{
				Description: toPtr("represents options specified by user for updating object."),
				Fields: schema.ObjectTypeFields{
					"legalHold": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"metadata": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"retention": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("SetStorageObjectRetentionOptions")).Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
		},
		Functions: []schema.FunctionInfo{
			{
				Name:        "downloadStorageObject",
				Description: toPtr("returns a stream of the object data. Most of the common errors occur when reading the stream."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("Bytes")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"headers": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"partNumber": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"requestParams": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "downloadStorageObjectText",
				Description: toPtr("returns the object content in plain text. Use this function only if you know exactly the file as an text file."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("String")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"headers": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"partNumber": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"requestParams": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storageBucket",
				Description: toPtr("gets a bucket by name."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("StorageBucket")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
				},
			},
			{
				Name:        "storageBucketExists",
				Description: toPtr("checks if a bucket exists."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
				},
			},
			{
				Name:        "storageBuckets",
				Description: toPtr("list all buckets."),
				ResultType:  schema.NewNamedType("StorageBucketListResults").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"maxResults": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"prefix": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"startAfter": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageBucketFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storageDeletedObjects",
				Description: toPtr("list deleted objects in a bucket."),
				ResultType:  schema.NewNamedType("StorageObjectListResults").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"hierarchy": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"maxResults": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"prefix": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"startAfter": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storageIncompleteUploads",
				Description: toPtr("list partially uploaded objects in a bucket."),
				ResultType:  schema.NewArrayType(schema.NewNamedType("StorageObjectMultipartInfo")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"prefix": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
			{
				Name:        "storageObject",
				Description: toPtr("fetches metadata of an object."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("StorageObject")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"headers": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"partNumber": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"requestParams": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storageObjects",
				Description: toPtr("lists objects in a bucket."),
				ResultType:  schema.NewNamedType("StorageObjectListResults").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"hierarchy": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"maxResults": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"prefix": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"startAfter": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storagePresignedDownloadUrl",
				Description: toPtr("generates a presigned URL for HTTP GET operations. Browsers/Mobile clients may point to this URL to directly download objects even if the bucket is private. This presigned URL can have an associated expiration time in seconds after which it is no longer operational. The maximum expiry is 604800 seconds (i.e. 7 days) and minimum is 1 second."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("PresignedURLResponse")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"expiry": {
						Type: schema.NewNullableType(schema.NewNamedType("Duration")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"requestParams": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "storagePresignedUploadUrl",
				Description: toPtr("generates a presigned URL for HTTP PUT operations. Browsers/Mobile clients may point to this URL to upload objects directly to a bucket even if it is private. This presigned URL can have an associated expiration time in seconds after which it is no longer operational. The default expiry is set to 7 days."),
				ResultType:  schema.NewNullableType(schema.NewNamedType("PresignedURLResponse")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"expiry": {
						Type: schema.NewNullableType(schema.NewNamedType("Duration")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
		},
		Procedures: []schema.ProcedureInfo{
			{
				Name:        "composeStorageObject",
				Description: toPtr("creates an object by concatenating a list of source objects using server-side copying."),
				ResultType:  schema.NewNamedType("StorageUploadInfo").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"dest": {
						Type: schema.NewNamedType("StorageCopyDestOptions").Encode(),
					},
					"sources": {
						Type: schema.NewArrayType(schema.NewNamedType("StorageCopySrcOptions")).Encode(),
					},
				},
			},
			{
				Name:        "copyStorageObject",
				Description: toPtr("creates or replaces an object through server-side copying of an existing object. It supports conditional copying, copying a part of an object and server-side encryption of destination and decryption of source. To copy multiple source objects into a single destination object see the ComposeObject API."),
				ResultType:  schema.NewNamedType("StorageUploadInfo").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"dest": {
						Type: schema.NewNamedType("StorageCopyDestOptions").Encode(),
					},
					"source": {
						Type: schema.NewNamedType("StorageCopySrcOptions").Encode(),
					},
				},
			},
			{
				Name:        "createStorageBucket",
				Description: toPtr("creates a new bucket."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"name": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"objectLock": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"region": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"tags": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
				},
			},
			{
				Name:        "removeIncompleteStorageUpload",
				Description: toPtr("removes a partially uploaded object."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			{
				Name:        "removeStorageBucket",
				Description: toPtr("removes a bucket, bucket should be empty to be successfully removed."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
				},
			},
			{
				Name:        "removeStorageObject",
				Description: toPtr("removes an object with some specified options."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"forceDelete": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"governanceBypass": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"softDelete": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"versionId": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "removeStorageObjects",
				Description: toPtr("remove a list of objects obtained from an input channel. The call sends a delete request to the server up to 1000 objects at a time. The errors observed are sent over the error channel."),
				ResultType:  schema.NewArrayType(schema.NewNamedType("RemoveStorageObjectError")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"governanceBypass": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"hierarchy": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"maxResults": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"prefix": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"startAfter": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "restoreStorageObject",
				Description: toPtr("restore a soft-deleted object."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "updateStorageBucket",
				Description: toPtr("updates the bucket's configuration."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"encryption": {
						Type: schema.NewNullableType(schema.NewNamedType("ServerSideEncryptionConfiguration")).Encode(),
					},
					"lifecycle": {
						Type: schema.NewNullableType(schema.NewNamedType("ObjectLifecycleConfiguration")).Encode(),
					},
					"objectLock": {
						Type: schema.NewNullableType(schema.NewNamedType("SetStorageObjectLockConfig")).Encode(),
					},
					"tags": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versioningEnabled": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
				},
			},
			{
				Name:        "updateStorageObject",
				Description: toPtr("updates the object's configuration."),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"legalHold": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"metadata": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"retention": {
						Type: schema.NewNullableType(schema.NewNamedType("SetStorageObjectRetentionOptions")).Encode(),
					},
					"tags": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"versionId": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "uploadStorageObject",
				Description: toPtr("uploads object that are less than 128MiB in a single PUT operation. For objects that are greater than 128MiB in size, PutObject seamlessly uploads the object as parts of 128MiB or more depending on the actual file size. The max upload size for an object is 5TB."),
				ResultType:  schema.NewNamedType("StorageUploadInfo").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"data": {
						Type: schema.NewNamedType("Bytes").Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"options": {
						Type: schema.NewNullableType(schema.NewNamedType("PutStorageObjectOptions")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
			{
				Name:        "uploadStorageObjectText",
				Description: toPtr("uploads object in plain text to the storage server. The file content is not encoded to base64 so the input size is smaller than 30%."),
				ResultType:  schema.NewNamedType("StorageUploadInfo").Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"bucket": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"clientId": {
						Type: schema.NewNullableType(schema.NewNamedType("StorageClientID")).Encode(),
					},
					"data": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"object": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"options": {
						Type: schema.NewNullableType(schema.NewNamedType("PutStorageObjectOptions")).Encode(),
					},
					"where": {
						Type: schema.NewNullableType(schema.NewPredicateType("StorageObjectFilter")).Encode(),
					},
				},
			},
		},
		ScalarTypes: schema.SchemaResponseScalarTypes{
			"Boolean": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationBoolean().Encode(),
			},
			"Bytes": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationBytes().Encode(),
			},
			"ChecksumType": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"SHA256", "SHA1", "CRC32", "CRC32C", "CRC64NVME", "FullObjectCRC32", "FullObjectCRC32C", "None"}).Encode(),
			},
			"Date": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationDate().Encode(),
			},
			"Duration": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationJSON().Encode(),
			},
			"GoogleStorageRPO": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"DEFAULT", "ASYNC_TURBO"}).Encode(),
			},
			"Int32": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt32().Encode(),
			},
			"Int64": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt64().Encode(),
			},
			"JSON": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationJSON().Encode(),
			},
			"StorageClientID": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationString().Encode(),
			},
			"StorageObjectReplicationStatus": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"COMPLETED", "PENDING", "FAILED", "REPLICA"}).Encode(),
			},
			"StorageRetentionMode": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"Locked", "Unlocked", "Mutable", "Delete"}).Encode(),
			},
			"StorageRetentionValidityUnit": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"DAYS", "YEARS"}).Encode(),
			},
			"String": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationString().Encode(),
			},
			"TimestampTZ": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationTimestampTZ().Encode(),
			},
		},
	}
}
