name: Release container definition
on:
  push:
    tags:
      - "*"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: hasura/ndc-storage

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  release-image:
    name: Release ndc-storage image
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get-version
        run: |
          echo "tagged_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract metadata (tags, labels) for Docker
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.get-version.outputs.tagged_version }}

  build-cli-binaries:
    name: build the CLI binaries
    runs-on: ubuntu-latest
    needs: [release-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: build the CLI
        run: |
          VERSION="$GITHUB_REF_NAME" make ci-build-configuration
          mkdir release
          .github/scripts/plugin-manifest.sh
          mv _output/* release

      - uses: actions/upload-artifact@v4
        with:
          path: release/manifest.yaml
          if-no-files-found: error
          name: plugin-manifest

      - uses: actions/upload-artifact@v4
        with:
          path: release/hasura-ndc-storage-*
          if-no-files-found: error
          name: artifact

      - name: Get version from tag
        id: get-version
        run: |
          echo "tagged_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build connector definition
        run: |
          ./scripts/build-manifest.sh
        env:
          VERSION: ${{ steps.get-version.outputs.tagged_version }}

      - name: create a draft release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ steps.get-version.outputs.tagged_version }}
          artifacts: release/*
